# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - develop
      - feature/**
  pull_request:
    branches:
      - master

env:
  repository: rtomchinsky/deno-dummy

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Define type
        run: |
          if [[ $GITHUB_REF == refs/pull/* ]]; then
            echo '::set_env name=CREATE_RELEASE::true'
          fi
      - uses: actions/checkout@v2
      - name: Setup Deno environment
        uses: denolib/setup-deno@v1.3.0
        with:
          deno-version: v1.1.1
      - name: Lint
        run: deno lint --unstable
      - name: Docker build
        uses: docker/build-push-action@v1
        with:
          repository: ${{ env.repository }}
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          tag_with_sha: true
      - name: Create prerelease
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          # ideally we'd calculate these with conventional commits
          tag_name: v${GITHUB_SHA}
          release_name: v${GITHUB_SHA}
